services:
  postgres:
    image: postgres:16
    container_name: tarefa-postgres
    environment:
      POSTGRES_DB: tarefadb
      POSTGRES_USER: tarefa
      POSTGRES_PASSWORD: tarefa
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  tomcat:
    build: .
    container_name: sigtarefa-server
    ports:
      - "8080:8080"
    volumes:
      - ./target/sigtarefa.war:/usr/local/tomcat/webapps/sigtarefa.war

    depends_on:
      - postgres