services:
  postgres:
    image: postgres
    container_name: tarefa-postgres
    environment:
      POSTGRES_DB: tarefadb
      POSTGRES_USER: tarefa
      POSTGRES_PASSWORD: tarefa
    ports:
      - "5432:5432"

  tomcat:
    image: tomcat:9.0-jdk21
    container_name: sigtarefa-server
    ports:
      - "8080:8080"
    volumes:
      - ./target/sigtarefa.war:/usr/local/tomcat/webapps/sigtarefa.war
    depends_on:
      - postgres